import Link from "next/link";
import { notFound } from "next/navigation";
import { can, getSessionUser, isSuperAdmin, roleLabels } from "@/lib/auth";
import { getStudentAccountDetail } from "@/lib/admin-student-accounts";
import { Denied } from "@/components/admin/Denied";
import { FieldLabel, Input } from "@/components/ui/Input";
import { AccountDeleteForm } from "@/components/admin/AccountDeleteForm";
import { formatPrice, toFa } from "@/lib/format";
import { deleteRegisteredStudentAccount, revokeStudentSessionsAction, updateStudentAccountAction } from "../actions";

const date = (value: unknown) => value ? new Date(String(value)).toLocaleString("fa-IR") : "—";
const errorMessages: Record<string, string> = { "invalid-phone": "شماره موبایل معتبر نیست.", "duplicate-phone": "این شماره قبلاً برای حساب دیگری ثبت شده است.", "protected-account": "این حساب قابل حذف نیست.", confirmation: "عبارت تأیید حذف صحیح نبود." };
export default async function StudentDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ error?: string; saved?: string }> }) {
  const me = await getSessionUser(); if (!can(me, "students")) return <Denied />; const { id } = await params; const query = await searchParams; const detail = await getStudentAccountDetail(id); if (!detail) notFound(); const owner = isSuperAdmin(me); const u = detail.user;
  return <div className="space-y-5">
    <div><Link href="/admin/students" className="text-sm font-bold text-teal-700">بازگشت به هنرجویان</Link><h1 className="mt-2 text-2xl font-black text-navy-900">حساب {u.name}</h1><p className="mt-1 text-xs text-ink-500" dir="ltr">{u.id}</p></div>
    {query.error && <p role="alert" className="rounded-xl bg-madder-50 p-3 text-sm font-bold text-madder-800">{errorMessages[query.error] ?? "عملیات انجام نشد."}</p>}
    {query.saved && <p className="rounded-xl bg-teal-50 p-3 text-sm font-bold text-teal-800">تغییرات با موفقیت ذخیره شد.</p>}
    <section className="rounded-2xl bg-card p-5 shadow-card ring-1 ring-ink-900/5"><h2 className="font-black text-navy-900">اطلاعات حساب</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><Info label="نقش" value={roleLabels[u.role]} /><Info label="وضعیت" value={u.disabled ? "غیرفعال" : "فعال"} /><Info label="تاریخ ثبت‌نام" value={date(u.createdAt)} /><Info label="آخرین ورود" value={date(u.lastLoginAt)} /><Info label="شماره" value={u.phone} /><Info label="ایمیل" value={u.email ?? "—"} /><Info label="نشست فعال" value={toFa(detail.sessions.active)} /><Info label="آخرین فعالیت نشست" value={date(detail.sessions.lastActivity)} /></dl></section>
    {owner ? <form action={updateStudentAccountAction} className="rounded-2xl bg-card p-5 shadow-card ring-1 ring-ink-900/5"><input type="hidden" name="id" value={id}/><input type="hidden" name="previousPhone" value={u.phone}/><h2 className="font-black text-navy-900">ویرایش اطلاعات امن</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><FieldLabel htmlFor="name">نام و نام خانوادگی</FieldLabel><Input id="name" name="name" defaultValue={u.name} required /></div><div><FieldLabel htmlFor="phone">شماره موبایل</FieldLabel><Input id="phone" name="phone" defaultValue={u.phone} required dir="ltr" className="text-left" /></div><div><FieldLabel htmlFor="email">ایمیل</FieldLabel><Input id="email" name="email" type="email" defaultValue={u.email ?? ""} dir="ltr" className="text-left" /></div><label className="flex items-center gap-2 self-end pb-2 text-sm font-bold"><input type="checkbox" name="enabled" defaultChecked={!u.disabled}/> حساب فعال باشد</label></div><p className="mt-3 text-xs leading-6 text-amber-800">شماره توسط مدیر اصلاح شده و مالکیت پیامکی آن هنوز تأیید نشده است. تغییر شماره یا غیرفعال‌سازی همه نشست‌ها را باطل می‌کند.</p><button className="mt-4 h-10 rounded-xl bg-teal-600 px-5 text-sm font-bold text-white hover:bg-teal-700">ذخیره تغییرات</button></form> : <p className="rounded-xl bg-sand-100 p-4 text-sm text-ink-600">مشاهده برای شما مجاز است؛ تغییرات حساس فقط توسط مدیر ارشد انجام می‌شود.</p>}
    <section className="grid gap-4 lg:grid-cols-2"><List title="دسترسی آموزشی" items={detail.enrollments.map((e) => `${e.course_slug} · ${date(e.created_at)}`)} /><List title="سفارش‌ها و پرداخت‌ها" items={[...detail.orders.map((o) => `${o.id} · ${formatPrice(Number(o.amount))} · ${o.status}`), ...detail.payments.map((p) => `${p.id} · ${formatPrice(Number(p.amount))} · ${p.status}`)]} /><List title="گواهی‌ها" items={detail.certificates.map((c) => `${c.course_title} · ${c.code} · ${date(c.issued_at)}`)} /><List title="سوابق پشتیبانی" items={[...detail.tickets.map((t) => `تیکت ${t.id} · ${t.status}`), ...detail.submissions.map((s) => `تمرین ${s.id} · ${s.status}`)]} /></section>
    {owner && <section className="space-y-4 rounded-2xl border border-madder-700/25 bg-card p-5"><div><h2 className="font-black text-madder-800">ناحیه خطر</h2><p className="mt-1 text-sm text-ink-600">حذف در صورت وجود سابقه مالی یا گواهی، حساب را می‌بندد و اطلاعات شخصی را ناشناس می‌کند؛ تاریخچه مالی تغییر نمی‌کند.</p></div><form action={revokeStudentSessionsAction}><input type="hidden" name="id" value={id}/><button className="h-10 rounded-xl border border-ink-900/15 px-4 text-sm font-bold hover:bg-sand-50">خروج از همه دستگاه‌ها</button></form><AccountDeleteForm action={deleteRegisteredStudentAccount} id={id}/></section>}
  </div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-ink-500">{label}</dt><dd className="mt-1 font-bold text-navy-900">{value}</dd></div>; }
function List({ title, items }: { title: string; items: string[] }) { return <section className="rounded-2xl bg-card p-5 shadow-card ring-1 ring-ink-900/5"><h2 className="font-black text-navy-900">{title}</h2>{items.length ? <ul className="mt-3 divide-y divide-ink-900/5 text-sm">{items.map((item, i) => <li key={`${item}-${i}`} className="py-2.5 break-words">{item}</li>)}</ul> : <p className="mt-3 text-sm text-ink-500">موردی ثبت نشده است.</p>}</section>; }
