import type { AboutContentSettings, AboutValueIcon, HomeContentSettings, SiteMedia, SiteSettings } from "./types";

const image = (src: string, alt: string): SiteMedia => ({ kind: "image", image: src, alt });
const ordered = <T extends { order: number }>(items: T[]) => [...items].filter(Boolean).sort((a, b) => a.order - b.order);
const text = (value: unknown, fallback = "", max = 1000) => typeof value === "string" ? value.trim().slice(0, max) : fallback;
const bool = (value: unknown, fallback = true) => typeof value === "boolean" ? value : fallback;
const safeHref = (value: unknown, fallback = "/") => { const v = text(value, fallback, 500); if (v.startsWith("/") && !v.startsWith("//")) return v; try { const u = new URL(v); return u.protocol === "http:" || u.protocol === "https:" ? u.toString() : fallback; } catch { return fallback; } };
export function safeEmbedUrl(value: unknown): string { const v = text(value, "", 1000); try { const u = new URL(v); if (!['http:','https:'].includes(u.protocol)) return ""; const host = u.hostname.replace(/^www\./, ""); return host === "youtube.com" || host === "youtu.be" || host === "aparat.com" || host.endsWith(".aparat.com") ? u.toString() : ""; } catch { return ""; } }

export function normalizeSiteMedia(value: unknown, fallback: SiteMedia): SiteMedia {
  if (!value || typeof value !== "object") return fallback;
  const v = value as Record<string, unknown>;
  if (v.kind === "image") { const src = text(v.image, "", 1000); return src.startsWith("/") || /^https?:\/\//.test(src) ? { kind: "image", image: src, alt: text(v.alt, "", 200) } : fallback; }
  if (v.kind === "video" && /^v-[a-z0-9-]+$/i.test(text(v.videoId))) return { kind: "video", videoId: text(v.videoId), poster: text(v.poster, "", 1000) || undefined, alt: text(v.alt, "", 200), autoplay: bool(v.autoplay, false), loop: bool(v.loop, false), muted: bool(v.autoplay, false) ? true : bool(v.muted, true) };
  if (v.kind === "embed") { const src = safeEmbedUrl(v.src); if (src) return { kind: "embed", src, poster: text(v.poster, "", 1000) || undefined, title: text(v.title, "ویدیوی معرفی", 200) }; }
  return fallback;
}

export const defaultHomeContent: HomeContentSettings = {
  trust: { enabled: true, stats: [{id:"students",value:"۱۲۰۰+",label:"هنرجو",hint:"از سراسر ایران",order:0},{id:"courses",value:"۳۵",label:"دوره",hint:"آنلاین و حضوری",order:1},{id:"years",value:"۱۵+",label:"سال تجربه",hint:"آموزش تخصصی",order:2},{id:"satisfaction",value:"۴٫۹",label:"رضایت",hint:"از ۵",order:3}], honors: ["حاضر در نمایشگاه بین‌المللی فرش دستباف تهران","دارای گواهی مهارت سازمان فنی‌وحرفه‌ای","همکاری با کارگاه‌های ایلات فارس و کردستان","داوری جشنواره ملی گلیم و گبه"].map((text,i)=>({id:`honor-${i}`,text,active:true,order:i})) },
  roadmap: { enabled:true, eyebrow:"نقشه راه", title:"مسیر فرش‌بافی؛ از شناخت ابزار تا فروش اثر", description:"یک مسیر پنج‌مرحله‌ای که دقیقاً می‌دانید هر ماه کجا هستید و قدم بعدی چیست.", checklist:["برنامه مشخص برای هر هفته","ارزیابی پایان هر مرحله توسط استاد","گواهی جداگانه برای هر سطح"].map((text,i)=>({id:`check-${i}`,text,active:true,order:i})), primaryCtaLabel:"مشاهده همه مسیرها",primaryCtaHref:"/paths",secondaryCtaLabel:"شروع مرحله اول",secondaryCtaHref:"/courses/carpet-weaving-foundations", stages:["شناخت ابزار|۲ هفته|آشنایی با دار، نخ و نقشه","گره و چله|۴ هفته|اجرای اصولی چله‌کشی و گره‌ها","بافت پروژه|۸ هفته|بافت یک اثر کامل با بازخورد استاد","پرداخت و تکمیل|۲ هفته|پرداخت نهایی و رفع ایراد","ارائه و فروش|پیوسته|عکاسی، قیمت‌گذاری و عرضه اثر"].map((row,i)=>{const [title,meta,description]=row.split("|");return{id:`stage-${i+1}`,title,meta,description,active:true,order:i}}) },
  spotlight:{enabled:true,instructorSlug:"",eyebrow:"— بنیان‌گذار و استاد اصلی",quote:"من از دوازده‌سالگی پای دار نشسته‌ام و هنوز هر روز چیزی تازه یاد می‌گیرم. فرش‌بافی فقط تکنیک نیست؛ صبر، دقت و عشق است.",experienceLabel:"تجربه بافت و آموزش",ctaLabel:"آشنایی با استاد",ctaHref:"/instructors",stats:[{id:"s1",value:"۸۶۰+",label:"هنرجو",order:0},{id:"s2",value:"۴",label:"دوره تخصصی",order:1},{id:"s3",value:"۲۰۰+",label:"اثر مرمت‌شده",order:2}]},
  workshop:{enabled:true,eyebrow:"کارگاه اسدزاده",title:"جایی که بوی پشم و رنگ می‌دهد",description:"کارگاه ما در قلب ارومیه؛ با دارهای چوبی قدیمی، پاتیل‌های رنگرزی و قفسه‌هایی پر از نخ‌های دست‌رنگ.",ctaLabel:"داستان کارگاه ما",ctaHref:"/about",items:[{id:"loom",media:image("/images/workshop-loom.jpg","دار قالی چوبی در کارگاه اسدزاده"),alt:"دار قالی چوبی در کارگاه اسدزاده",caption:"سالن بافت — ۱۲ دار فعال",active:true,order:0},{id:"threads",media:image("/images/workshop-threads.jpg","کلاف‌های نخ دست‌رنگ"),alt:"کلاف‌های نخ دست‌رنگ",caption:"انبار نخ‌های دست‌رنگ",active:true,order:1},{id:"dye",media:image("/images/course-dye.jpg","رنگرزی سنتی"),alt:"رنگرزی سنتی",caption:"بخش رنگرزی طبیعی",active:true,order:2}]},
  studentWorks:{enabled:true,eyebrow:"افتخار ما",title:"آثار هنرجویان",description:"این‌ها را کسانی بافته‌اند که چند ماه پیش از صفر شروع کردند.",items:[]},
  testimonials:{enabled:true,eyebrow:"نظر هنرجویان",title:"کسانی که از این راه رفته‌اند",description:"تجربه هنرجویان از دوره‌های اسدزاده",items:[]},
  finalCta:{enabled:true,eyebrow:"مشاوره رایگان انتخاب مسیر",title:"هنوز مطمئن نیستید از کجا شروع کنید؟",description:"در یک تماس کوتاه، سطح و هدفتان را بررسی می‌کنیم و بهترین مسیر را پیشنهاد می‌دهیم.",primaryCtaLabel:"رزرو مشاوره رایگان",primaryCtaHref:"/paths",showPhone:true,phoneLabel:"تماس مستقیم"},
};

export const defaultAboutContent: AboutContentSettings = {
  hero:{enabled:true,title:"داستان ما؛ سه نسل پای دار قالی",description:"اسدزاده یک خانواده بافنده است که حالا تجربه‌اش را تدریس می‌کند."},
  intro:{enabled:true,heading:"از تبریز تا ارومیه؛ از دار تا دوربین",paragraphs:[]},
  gallery:{enabled:true,items:[{id:"about-1",media:image("/images/workshop-loom.jpg","کارگاه بافت اسدزاده"),alt:"کارگاه بافت اسدزاده",active:true,order:0},{id:"about-2",media:image("/images/workshop-threads.jpg","نخ‌های دست‌رنگ"),alt:"نخ‌های دست‌رنگ",active:true,order:1},{id:"about-3",media:image("/images/hero-weaver.jpg","دست‌های استاد در حال بافت"),alt:"دست‌های استاد در حال بافت",active:true,order:2}]},
  timeline:{enabled:true,title:"خط زمانی ما",items:[["۱۳۴۸","اولین دار خانوادگی در تبریز برپا شد."],["۱۳۷۵","نسل دوم، کارگاه مرمت را در ارومیه راه انداخت."],["۱۳۹۰","اولین کلاس‌های آموزشی حضوری برگزار شد."],["۱۳۹۹","آموزش آنلاین آغاز شد."],["۱۴۰۵","جامعه هنرجویان و کارگاه توسعه یافت."]].map(([year,text],i)=>({id:`time-${i}`,year,text,active:true,order:i}))},
  values:{enabled:true,title:"ارزش‌های ما",items:[["hand-heart","اصالت","تکنیک‌های سنتی، بدون میان‌بر."],["graduation-cap","آموزش واقعی","تمرین، رفع‌اشکال و ارزیابی."],["leaf","احترام به طبیعت","ترویج رنگ طبیعی و مواد پایدار."],["medal","کیفیت بی‌مصالحه","کیفیت اثر بر سرعت مقدم است."]].map(([icon,title,text],i)=>({id:`value-${i}`,icon:icon as AboutValueIcon,title,text,active:true,order:i}))},
  ctas:[{label:"مشاهده دوره‌ها",href:"/courses",enabled:true},{label:"آشنایی با اساتید",href:"/instructors",enabled:true}],
};

function list(raw: unknown, max: number): Record<string, unknown>[] { return Array.isArray(raw) ? raw.filter(v=>v&&typeof v==="object").slice(0,max) as Record<string,unknown>[] : []; }
const id = (v: unknown, prefix: string, i: number) => /^[a-z0-9_-]{1,80}$/i.test(text(v)) ? text(v) : `${prefix}-${i}`;
export function normalizeHomeContent(raw: unknown): HomeContentSettings {
  const r=(raw&&typeof raw==="object"?raw:{}) as Record<string,Record<string,unknown>>, d=defaultHomeContent;
  const stats=(v:unknown,fb= d.trust.stats)=>{const a=list(v,12);return a.length?ordered(a.map((x,i)=>({id:id(x.id,"stat",i),value:text(x.value,"",30),label:text(x.label,"",80),hint:text(x.hint,"",120),active:bool(x.active,true),order:Number.isFinite(x.order)?Number(x.order):i}))):fb};
  const texts=(v:unknown,fb:typeof d.trust.honors,max=20)=>{const a=list(v,max);return a.length?ordered(a.map((x,i)=>({id:id(x.id,"text",i),text:text(x.text,"",300),active:bool(x.active,true),order:Number.isFinite(x.order)?Number(x.order):i}))):fb};
  const workshop=list(r.workshop?.items,12).map((x,i)=>({id:id(x.id,"media",i),media:normalizeSiteMedia(x.media,image("/images/workshop-loom.jpg","کارگاه")),alt:text(x.alt,"",200),caption:text(x.caption,"",200),active:bool(x.active,true),order:Number.isFinite(x.order)?Number(x.order):i}));
  return {trust:{enabled:bool(r.trust?.enabled,true),stats:stats(r.trust?.stats),honors:texts(r.trust?.honors,d.trust.honors)},roadmap:{...d.roadmap,...r.roadmap,enabled:bool(r.roadmap?.enabled,true),primaryCtaHref:safeHref(r.roadmap?.primaryCtaHref,d.roadmap.primaryCtaHref),secondaryCtaHref:safeHref(r.roadmap?.secondaryCtaHref,d.roadmap.secondaryCtaHref),checklist:texts(r.roadmap?.checklist,d.roadmap.checklist,10),stages:(()=>{const a=list(r.roadmap?.stages,12);return a.length?ordered(a.map((x,i)=>({id:id(x.id,"stage",i),title:text(x.title,"",120),meta:text(x.meta,"",80),description:text(x.description,"",500),active:bool(x.active,true),order:Number.isFinite(x.order)?Number(x.order):i}))):d.roadmap.stages})()},spotlight:{...d.spotlight,...r.spotlight,enabled:bool(r.spotlight?.enabled,true),ctaHref:safeHref(r.spotlight?.ctaHref,d.spotlight.ctaHref),stats:stats(r.spotlight?.stats,d.spotlight.stats)},workshop:{...d.workshop,...r.workshop,enabled:bool(r.workshop?.enabled,true),ctaHref:safeHref(r.workshop?.ctaHref,d.workshop.ctaHref),items:workshop.length?ordered(workshop):d.workshop.items},studentWorks:{...d.studentWorks,...r.studentWorks,enabled:bool(r.studentWorks?.enabled,true),items:ordered(list(r.studentWorks?.items,20).map((x,i)=>({id:id(x.id,"work",i),title:text(x.title,"",120),studentName:text(x.studentName,"",100),image:text(x.image,"",1000),description:text(x.description,"",400),course:text(x.course,"",120),active:bool(x.active,true),order:Number.isFinite(x.order)?Number(x.order):i})))},testimonials:{...d.testimonials,...r.testimonials,enabled:bool(r.testimonials?.enabled,true),items:ordered(list(r.testimonials?.items,20).map((x,i)=>({id:id(x.id,"testimonial",i),name:text(x.name,"",100),role:text(x.role,"",100),text:text(x.text,"",700),rating:Math.min(5,Math.max(1,Number(x.rating)||5)),active:bool(x.active,true),order:Number.isFinite(x.order)?Number(x.order):i})))},finalCta:{...d.finalCta,...r.finalCta,enabled:bool(r.finalCta?.enabled,true),primaryCtaHref:safeHref(r.finalCta?.primaryCtaHref,d.finalCta.primaryCtaHref),showPhone:bool(r.finalCta?.showPhone,true)}};
}

export function normalizeAboutContent(raw: unknown, legacyIntro: string[]): AboutContentSettings {
 const r=(raw&&typeof raw==="object"?raw:{}) as Record<string,Record<string,unknown>>,d=defaultAboutContent; const items=list(r.gallery?.items,6).map((x,i)=>({id:id(x.id,"about-media",i),media:normalizeSiteMedia(x.media,d.gallery.items[i%3].media),alt:text(x.alt,"",200),active:bool(x.active,true),order:Number.isFinite(x.order)?Number(x.order):i})); const icons=new Set<AboutValueIcon>(["hand-heart","graduation-cap","leaf","medal","star","award","shield","users"]);
 return {hero:{...d.hero,...r.hero,enabled:bool(r.hero?.enabled,true)},intro:{...d.intro,...r.intro,enabled:bool(r.intro?.enabled,true),paragraphs:(()=>{const a=list(r.intro?.paragraphs,12);return a.length?ordered(a.map((x,i)=>({id:id(x.id,"paragraph",i),text:text(x.text,"",1500),active:bool(x.active,true),order:Number.isFinite(x.order)?Number(x.order):i}))):legacyIntro.map((text,i)=>({id:`legacy-${i}`,text,active:true,order:i}))})()},gallery:{enabled:bool(r.gallery?.enabled,true),items:items.length?ordered(items):d.gallery.items},timeline:{...d.timeline,...r.timeline,enabled:bool(r.timeline?.enabled,true),items:(()=>{const a=list(r.timeline?.items,30);return a.length?ordered(a.map((x,i)=>({id:id(x.id,"time",i),year:text(x.year,"",30),text:text(x.text,"",500),active:bool(x.active,true),order:Number.isFinite(x.order)?Number(x.order):i}))):d.timeline.items})()},values:{...d.values,...r.values,enabled:bool(r.values?.enabled,true),items:(()=>{const a=list(r.values?.items,12);return a.length?ordered(a.map((x,i)=>({id:id(x.id,"value",i),icon:icons.has(x.icon as AboutValueIcon)?x.icon as AboutValueIcon:"star",title:text(x.title,"",100),text:text(x.text,"",500),active:bool(x.active,true),order:Number.isFinite(x.order)?Number(x.order):i}))):d.values.items})()},ctas:(()=>{const a=list(r.ctas,4);return a.length?a.map(x=>({label:text(x.label,"",80),href:safeHref(x.href,"/"),enabled:bool(x.enabled,true)})):d.ctas})()};
}

export function normalizedSiteContent(site: SiteSettings) { return { home: normalizeHomeContent(site.home), about: normalizeAboutContent(site.about, site.aboutIntro) }; }
