import { can, getSessionUser, isSuperAdmin } from "@/lib/auth";
import { Denied } from "@/components/admin/Denied";
import { FieldLabel, Input, Select, Textarea } from "@/components/ui/Input";
import { TableShell, Td } from "@/components/admin/TableShell";
import { integrationStatus } from "@/lib/integrations";
import { getSettings } from "@/lib/store";
import { NOTIFICATION_EVENTS } from "@/lib/notification-events";
import { listSmsDeliveryLogs, listSmsRules, listSmsTemplates } from "@/lib/sms-automation";
import { removeSmsRuleAction, removeSmsTemplateAction, saveSmsConnectionAction, testSmsTemplateAction, upsertSmsRuleAction, upsertSmsTemplateAction } from "./actions";

export const metadata = { title: "مرکز پیامک و اعلان‌ها" };
export default async function SmsCenterPage({ searchParams }: { searchParams: Promise<{ status?: string; event?: string; template?: string; saved?: string; error?: string }> }) {
  const user=await getSessionUser();if(!can(user,"notify"))return <Denied/>;const owner=isSuperAdmin(user);const query=await searchParams;const [templates,rules,logs]=await Promise.all([listSmsTemplates(),listSmsRules(),listSmsDeliveryLogs({status:query.status,eventId:query.event,templateId:query.template})]);const status=integrationStatus().sms;const settings=getSettings();
  return <div className="space-y-6"><header><h1 className="text-2xl font-black text-navy-900">مرکز پیامک و اعلان‌ها</h1><p className="mt-1 text-sm text-ink-500">اتصال ملی پیامک، الگوهای تأییدشده، اتصال رویدادها و گزارش تحویل</p></header>
    {query.saved&&<p className="rounded-xl bg-teal-50 p-3 text-sm font-bold text-teal-800">عملیات با موفقیت انجام شد.</p>}{query.error&&<p role="alert" className="rounded-xl bg-madder-50 p-3 text-sm font-bold text-madder-800">عملیات انجام نشد: {query.error}</p>}{status.credentialDecryptionFailed&&<p role="alert" className="rounded-xl bg-madder-50 p-3 text-sm font-bold text-madder-800">رمزگشایی اطلاعات اتصال ممکن نیست. احتمالاً APP_SECRET تغییر کرده است؛ برای فعال‌سازی دوباره، نام کاربری و رمز وب‌سرویس را مجدداً وارد و ذخیره کنید.</p>}
    <section className="rounded-2xl bg-card p-5 shadow-card ring-1 ring-ink-900/5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black text-navy-900">اتصال سرویس</h2><p className="mt-1 text-sm text-ink-500">ملی پیامک · {status.configured?"فعال":"ناقص یا غیرفعال"} · منبع فعال: {status.fromEnvironment?"Environment fallback":"Admin"}</p></div><span className={`rounded-lg px-3 py-1 text-xs font-bold ${status.configured?"bg-teal-50 text-teal-800":"bg-amber-50 text-amber-800"}`}>{status.configured?"آماده ارسال":"نیازمند تکمیل"}</span></div>{owner?<form action={saveSmsConnectionAction} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><FieldLabel htmlFor="sms-user">نام کاربری API</FieldLabel><Input id="sms-user" name="apiKey" placeholder={settings.sms.apiKey?"ذخیره شده — برای تغییر وارد کنید":""} autoComplete="off" dir="ltr"/></div><div><FieldLabel htmlFor="sms-pass">رمز وب‌سرویس</FieldLabel><Input id="sms-pass" name="secret" type="password" placeholder={settings.sms.secret?"ذخیره شده — برای تغییر وارد کنید":""} autoComplete="new-password" dir="ltr"/></div><div><FieldLabel htmlFor="sms-sender">خط خدماتی (اختیاری)</FieldLabel><Input id="sms-sender" name="sender" defaultValue={settings.sms.sender} dir="ltr"/></div><label className="flex items-center gap-2 self-end pb-3 text-sm font-bold"><input type="checkbox" name="enabled" defaultChecked={settings.sms.provider==="melipayamak"}/> اتصال فعال باشد</label><button className="h-10 rounded-xl bg-teal-600 px-5 text-sm font-bold text-white sm:col-span-2 lg:col-span-4 lg:justify-self-start">ذخیره اتصال</button></form>:<p className="mt-4 text-sm text-ink-500">تغییر اطلاعات اتصال فقط برای مدیر ارشد مجاز است.</p>}</section>
    <section className="space-y-3"><h2 className="text-lg font-black text-navy-900">الگوها</h2>{owner&&<details className="rounded-2xl bg-card p-4 ring-1 ring-ink-900/5"><summary className="cursor-pointer font-bold text-teal-700">+ افزودن الگوی جدید</summary><form action={upsertSmsTemplateAction} className="mt-4 grid gap-4 sm:grid-cols-2"><div><FieldLabel htmlFor="tpl-name">نام الگو</FieldLabel><Input id="tpl-name" name="name" required/></div><div><FieldLabel htmlFor="tpl-body">Body ID</FieldLabel><Input id="tpl-body" name="bodyId" type="number" min="1" required dir="ltr"/></div><div><FieldLabel htmlFor="tpl-vars">متغیرها به ترتیب</FieldLabel><Input id="tpl-vars" name="variableOrder" required dir="ltr" placeholder="code, expiresIn"/></div><div><FieldLabel htmlFor="tpl-desc">توضیح</FieldLabel><Input id="tpl-desc" name="description"/></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" name="enabled" defaultChecked/> فعال</label><button className="h-10 rounded-xl bg-teal-600 px-5 text-sm font-bold text-white sm:justify-self-start">ثبت الگو</button></form></details>}<TableShell head={["نام","Body ID","متغیرها","وضعیت","عملیات"]}>{templates.map(t=><tr key={t.id}><Td className="font-bold">{t.name}</Td><Td dir="ltr">{t.providerTemplateId}</Td><Td dir="ltr" className="text-xs">{t.variableOrder.join(", ")}</Td><Td>{t.enabled?"فعال":"غیرفعال"}</Td><Td>{owner&&<form action={removeSmsTemplateAction}><input type="hidden" name="id" value={t.id}/><button className="text-xs font-bold text-madder-700">حذف</button></form>}</Td></tr>)}</TableShell></section>
    <section className="space-y-3"><h2 className="text-lg font-black text-navy-900">اتصال رویدادها</h2>{owner&&<form action={upsertSmsRuleAction} className="grid gap-4 rounded-2xl bg-card p-4 ring-1 ring-ink-900/5 sm:grid-cols-2 lg:grid-cols-4"><div><FieldLabel htmlFor="rule-event">رویداد</FieldLabel><Select id="rule-event" name="eventId">{Object.entries(NOTIFICATION_EVENTS).map(([id,e])=><option key={id} value={id}>{e.label} — {id}</option>)}</Select></div><div><FieldLabel htmlFor="rule-template">الگو</FieldLabel><Select id="rule-template" name="templateId">{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</Select></div><div><FieldLabel htmlFor="rule-priority">اولویت</FieldLabel><Input id="rule-priority" name="priority" type="number" defaultValue="100"/></div><label className="flex items-center gap-2 self-end pb-3 text-sm font-bold"><input type="checkbox" name="enabled" defaultChecked/> فعال</label><button className="h-10 rounded-xl bg-teal-600 px-5 text-sm font-bold text-white lg:col-span-4 lg:justify-self-start">+ افزودن اتصال جدید</button></form>}<TableShell head={["رویداد","متغیرهای رویداد","الگو","اولویت","عملیات"]}>{rules.map(r=><tr key={r.id}><Td><b>{NOTIFICATION_EVENTS[r.eventId].label}</b><div dir="ltr" className="mt-1 text-xs text-ink-500">{r.eventId}</div></Td><Td dir="ltr" className="text-xs">{NOTIFICATION_EVENTS[r.eventId].variables.join(", ")}</Td><Td>{templates.find(t=>t.id===r.templateId)?.name??r.templateId}</Td><Td>{r.priority}</Td><Td>{owner&&<form action={removeSmsRuleAction}><input type="hidden" name="id" value={r.id}/><button className="text-xs font-bold text-madder-700">حذف</button></form>}</Td></tr>)}</TableShell></section>
    <section className="rounded-2xl bg-card p-5 shadow-card ring-1 ring-ink-900/5"><h2 className="font-black text-navy-900">ارسال پیامک آزمایشی</h2><p className="mt-1 text-xs text-ink-500">فقط یک ارسال، بدون تلاش خودکار مجدد؛ نتیجه در گزارش ثبت می‌شود.</p><form action={testSmsTemplateAction} className="mt-4 grid gap-4 sm:grid-cols-2"><div><FieldLabel htmlFor="test-phone">شماره تحت کنترل اپراتور</FieldLabel><Input id="test-phone" name="phone" required dir="ltr"/></div><div><FieldLabel htmlFor="test-event">رویداد دارای اتصال</FieldLabel><Select id="test-event" name="eventId">{Object.entries(NOTIFICATION_EVENTS).map(([id,e])=><option key={id} value={id}>{e.label}</option>)}</Select></div><div className="sm:col-span-2"><FieldLabel htmlFor="test-vars">مقادیر متغیرها</FieldLabel><Textarea id="test-vars" name="variables" dir="ltr" placeholder="code=123456;expiresIn=5" required/></div><button className="h-10 rounded-xl bg-navy-900 px-5 text-sm font-bold text-white sm:justify-self-start">تأیید و ارسال یک پیامک</button></form></section>
    <section className="space-y-3"><h2 className="text-lg font-black text-navy-900">گزارش ارسال</h2><form className="flex flex-wrap gap-2"><Select name="status" defaultValue={query.status??""} className="w-auto"><option value="">همه وضعیت‌ها</option><option value="sent">ارسال‌شده</option><option value="failed">ناموفق</option><option value="skipped">ردشده</option></Select><button className="h-11 rounded-xl border border-ink-900/10 px-4 text-sm font-bold">اعمال فیلتر</button></form><TableShell head={["زمان","رویداد","الگو","گیرنده","وضعیت"]}>{logs.map(l=><tr key={l.id}><Td>{new Date(l.createdAt).toLocaleString("fa-IR")}</Td><Td dir="ltr" className="text-xs">{l.eventId}</Td><Td>{templates.find(t=>t.id===l.templateId)?.name??l.templateId}</Td><Td dir="ltr">{l.recipientMasked}</Td><Td>{l.status}</Td></tr>)}</TableShell>{!logs.length&&<p className="rounded-xl bg-sand-50 p-6 text-center text-sm text-ink-500">هنوز گزارشی ثبت نشده است.</p>}</section>
  </div>;
}
