import fs from "node:fs";
import { describe, expect, it } from "vitest";
import { adjacentJalaliMonth, classCategory, classMatchesScheduleFilters, currentJalaliMonth, deriveClassCalendarEvents, deriveClassScheduleStatus, jalaliFirstWeekday, jalaliMonthGrid, jalaliMonthLength } from "../class-schedule";
import type { InPersonClass } from "../types";

const base: InPersonClass = { slug: "kilim", title: "گلیم‌بافی (حضوری)", category: "گلیم", instructor: "استاد الف", instructorSlug: "teacher-a", startDate: "2026-09-23", days: "شنبه", time: "10:00", sessions: 2, sessionSchedule: [], capacity: 10, remaining: 8, location: "کارگاه", price: 1, image: "/x", excerpt: "", includes: [] };

describe("class schedule", () => {
  it("derives enrollment and lifecycle statuses", () => { expect(deriveClassScheduleStatus(base, new Date("2026-01-01"))).toBe("open"); expect(deriveClassScheduleStatus({ ...base, remaining: 2 }, new Date("2026-01-01"))).toBe("limited"); expect(deriveClassScheduleStatus({ ...base, remaining: 0 }, new Date("2026-01-01"))).toBe("full"); expect(deriveClassScheduleStatus({ ...base, startDate: "2025-01-01" }, new Date("2026-01-01"))).toBe("started"); expect(deriveClassScheduleStatus({ ...base, sessionSchedule: [{ id: "1", date: "2025-01-01", startTime: "10:00", endTime: "11:00", status: "completed" }] }, new Date("2026-01-01"))).toBe("completed"); });
  it("calculates first weekday, month length and leap Esfand", () => { expect(jalaliFirstWeekday(1405, 1)).toBe(0); expect(jalaliMonthLength(1405, 1)).toBe(31); expect(jalaliMonthLength(1399, 12)).toBe(30); expect(jalaliMonthLength(1400, 12)).toBe(29); });
  it("builds complete 5-row and 6-row grids with adjacent dates", () => { const five = jalaliMonthGrid(1405, 1); const six = jalaliMonthGrid(1405, 3); expect(five).toHaveLength(35); expect(six).toHaveLength(42); expect(five.filter(cell => cell.inCurrentMonth)).toHaveLength(31); expect(six.every(cell => /^\d{4}-\d{2}-\d{2}$/.test(cell.date))).toBe(true); });
  it("rolls between Farvardin and Esfand", () => { expect(adjacentJalaliMonth(1405, 1, -1)).toEqual({ year: 1404, month: 12 }); expect(adjacentJalaliMonth(1405, 12, 1)).toEqual({ year: 1406, month: 1 }); });
  it("tracks the current Jalali month", () => { expect(currentJalaliMonth(new Date("2026-09-20T00:00:00Z"))).toEqual({ year: 1405, month: 6 }); expect(classCategory(base)).toBe("گلیم"); });
});

describe("calendar event derivation", () => {
  const scheduled: InPersonClass = { ...base, sessionSchedule: [{ id: "normal", date: "2026-09-23", startTime: "10:00", endTime: "12:00", title: "جلسه اول", status: "scheduled" }, { id: "cancelled", date: "2026-09-23", startTime: "13:00", endTime: "14:00", status: "cancelled" }, { id: "postponed", date: "2026-09-24", startTime: "10:00", endTime: "12:00", status: "postponed" }, { id: "completed", date: "2026-09-25", startTime: "10:00", endTime: "12:00", status: "completed" }] };
  const events = deriveClassCalendarEvents([scheduled], new Map([["teacher-a", "استاد الف"]]));
  it("places class start and sessions on exact Gregorian/Jalali dates", () => { expect(events.find(event => event.type === "class-start")).toMatchObject({ date: "2026-09-23", jalaliDate: "1405/07/01", href: "/classes/kilim" }); expect(events.find(event => event.sessionId === "normal")).toMatchObject({ date: "2026-09-23", title: "جلسه اول" }); });
  it("places a legacy display-only start date in the operational year", () => { expect(deriveClassCalendarEvents([{ ...base, startDate: "۲۵ مهر" }], new Map(), 1405)[0]).toMatchObject({ date: "2026-10-17", jalaliDate: "1405/07/25" }); });
  it("supports multiple events per day and every session status", () => { expect(events.filter(event => event.date === "2026-09-23")).toHaveLength(3); expect(events.find(event => event.sessionId === "cancelled")?.type).toBe("cancelled-session"); expect(events.find(event => event.sessionId === "postponed")?.type).toBe("postponed-session"); expect(events.find(event => event.sessionId === "completed")?.status).toBe("completed"); });
  it("applies instructor, category and search filters consistently", () => { const common = { year: 1405, month: 7 }; expect(classMatchesScheduleFilters(scheduled, { ...common, instructor: "teacher-a" }, ["استاد الف"])).toBe(true); expect(classMatchesScheduleFilters(scheduled, { ...common, instructor: "teacher-b" }, ["استاد الف"])).toBe(false); expect(classMatchesScheduleFilters(scheduled, { ...common, category: "فرش" }, ["استاد الف"])).toBe(false); expect(classMatchesScheduleFilters(scheduled, { ...common, query: "ناموجود" }, ["استاد الف"])).toBe(false); expect(classMatchesScheduleFilters(scheduled, { ...common, query: "استاد الف" }, ["استاد الف"])).toBe(true); });
  it("keeps canonical route and responsive calendar architecture", () => { const page = fs.readFileSync("app/classes/schedule/page.tsx", "utf8"); expect(page).toContain('canonical: `${appUrl()}/classes/schedule`'); expect(page).toContain("data-calendar-grid"); expect(page).toContain("data-mobile-calendar"); expect(fs.readFileSync("app/sitemap.ts", "utf8")).toContain('"/classes/schedule"'); });
});
