import { describe, expect, it } from "vitest";
import { loginSchema, mfaSchema, registerSchema, zTotpCode } from "@/lib/validation/auth";
import { addStaffSchema, isAssignableRole, updateRoleSchema } from "@/lib/validation/admin";
import { validate, zPhone, zPostalCode, zToman } from "@/lib/validation/schema";
import { bool, num, numAllowZero, oneOf, str } from "@/lib/validation/form";

function form(entries: Record<string, string>): FormData {
  const fd = new FormData();
  for (const [key, value] of Object.entries(entries)) fd.set(key, value);
  return fd;
}

describe("phone numbers", () => {
  it("normalises Persian digits and the +98 prefix", () => {
    expect(validate(zPhone, "۰۹۱۲۰۰۰۰۰۰۱")).toEqual({ ok: true, data: "09120000001" });
    expect(validate(zPhone, "+989120000001")).toEqual({ ok: true, data: "+989120000001" });
    expect(validate(zPhone, "0912-000-0001")).toEqual({ ok: true, data: "09120000001" });
  });

  it("rejects numbers that are not Iranian mobiles", () => {
    for (const bad of ["02112345678", "12345678", "0912000000", "", "javascript:alert(1)"]) {
      expect(validate(zPhone, bad).ok).toBe(false);
    }
  });
});

describe("login schema", () => {
  it("accepts a well-formed login", () => {
    const result = validate(loginSchema, { phone: "09120000001", password: "secret", next: "/dashboard" });
    expect(result).toEqual({ ok: true, data: { phone: "09120000001", password: "secret", next: "/dashboard" } });
  });

  it("refuses an open redirect in the next path", () => {
    for (const bad of ["//evil.example.com", "https://evil.example.com", "/\\evil.example.com"]) {
      const result = validate(loginSchema, { phone: "09120000001", password: "x", next: bad });
      expect(result.ok, bad).toBe(false);
    }
  });

  it("allows a same-site absolute path", () => {
    expect(validate(loginSchema, { phone: "09120000001", password: "x", next: "/dashboard/orders" }).ok).toBe(true);
  });
});

describe("registration schema", () => {
  it("rejects a short password", () => {
    const result = validate(registerSchema, { name: "سارا", phone: "09120000001", password: "short" });
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.message).toContain("۱۰");
  });

  it("rejects a control-character name", () => {
    expect(validate(registerSchema, { name: "\u0000\u0001", phone: "09120000001", password: "a-long-enough-pass" }).ok).toBe(
      false,
    );
  });
});

describe("2FA codes", () => {
  it("accepts the formats the app actually issues", () => {
    expect(validate(zTotpCode, "۱۲۳۴۵۶")).toEqual({ ok: true, data: "123456" });
    // Recovery codes are XXXX-XXXX, generated by lib/totp.ts.
    expect(validate(mfaSchema, { code: "a1b2-c3d4", next: "" }).ok).toBe(true);
    expect(validate(mfaSchema, { code: "123456", next: "" }).ok).toBe(true);
  });

  it("rejects anything else", () => {
    for (const bad of ["12345", "1234567", "abcd-efgh-ij", "", "' OR 1=1 --"]) {
      expect(validate(mfaSchema, { code: bad, next: "" }).ok, bad).toBe(false);
    }
  });
});

describe("money and postal codes", () => {
  it("keeps money a non-negative integer", () => {
    expect(validate(zToman, "1500000")).toEqual({ ok: true, data: 1_500_000 });
    for (const bad of ["-1", "1.5", "abc"]) expect(validate(zToman, bad).ok, bad).toBe(false);
  });

  it("accepts 5 or 10 digit postal codes", () => {
    expect(validate(zPostalCode, "۱۲۳۴۵۶۷۸۹۰").ok).toBe(true);
    expect(validate(zPostalCode, "12345").ok).toBe(true);
    expect(validate(zPostalCode, "1234").ok).toBe(false);
  });
});

describe("role assignment — the privilege boundary", () => {
  it("never accepts super_admin or admin through the role-change form", () => {
    for (const bad of ["super_admin", "admin", "root", "", "manager "]) {
      expect(validate(updateRoleSchema, { id: "u-1", role: bad }).ok, bad).toBe(false);
    }
  });

  it("accepts only the assignable roles", () => {
    for (const good of ["manager", "editor", "support", "instructor", "student"]) {
      expect(validate(updateRoleSchema, { id: "u-1", role: good }).ok, good).toBe(true);
    }
  });

  it("will not mint staff with a privileged role", () => {
    const base = { name: "همکار", phone: "09120000009", password: "a-long-enough-pass" };
    expect(validate(addStaffSchema, { ...base, role: "admin" }).ok).toBe(false);
    expect(validate(addStaffSchema, { ...base, role: "super_admin" }).ok).toBe(false);
    expect(validate(addStaffSchema, { ...base, role: "student" }).ok).toBe(false);
    expect(validate(addStaffSchema, { ...base, role: "support" }).ok).toBe(true);
  });

  it("refuses a short staff password", () => {
    expect(
      validate(addStaffSchema, { name: "همکار", phone: "09120000009", password: "short", role: "support" }).ok,
    ).toBe(false);
  });

  it("treats super_admin as never assignable", () => {
    expect(isAssignableRole("super_admin")).toBe(false);
    expect(isAssignableRole("admin")).toBe(false);
    expect(isAssignableRole("support")).toBe(true);
  });
});

describe("FormData readers", () => {
  it("trims text and caps its length", () => {
    expect(str(form({ title: "  گلیم  " }), "title")).toBe("گلیم");
    expect(str(form({ title: "x".repeat(500) }), "title", 100)).toBe("");
  });

  it("strips control characters", () => {
    expect(str(form({ title: "ab\u0000cd" }), "title")).toBe("abcd");
  });

  it("reads Persian digits as numbers", () => {
    expect(num(form({ price: "۱۵۰۰۰۰۰" }), "price", 0)).toBe(1_500_000);
    expect(num(form({ price: "abc" }), "price", 42)).toBe(42);
    expect(num(form({ price: "-5" }), "price", 0)).toBe(0);
  });

  it("allows zero where zero is meaningful", () => {
    expect(numAllowZero(form({ stock: "0" }), "stock", 99)).toBe(0);
    expect(numAllowZero(form({ stock: "" }), "stock", 99)).toBe(99);
  });

  it("rejects values outside the declared range", () => {
    expect(numAllowZero(form({ discount: "150" }), "discount", 0, { max: 100 })).toBe(0);
  });

  it("only treats explicit checkbox spellings as true", () => {
    for (const truthy of ["on", "1", "true"]) expect(bool(form({ active: truthy }), "active"), truthy).toBe(true);
    for (const falsy of ["", "0", "false", "yes", "TRUE"]) expect(bool(form({ active: falsy }), "active"), falsy).toBe(
      false,
    );
  });

  it("returns undefined for a value outside the allowed set", () => {
    expect(oneOf(form({ status: "paid" }), "status", ["paid", "pending"] as const)).toBe("paid");
    expect(oneOf(form({ status: "hacked" }), "status", ["paid", "pending"] as const)).toBeUndefined();
  });
});
