"use client";

import { useState } from "react";
import type { AboutContentSettings, VideoAsset } from "@/lib/types";
import { SiteMediaEditor } from "./SiteMediaEditor";
import { ReorderControls, reorderItems, StructuredListEditor } from "./StructuredListEditor";

const input="h-10 w-full rounded-lg border border-ink-900/10 bg-white px-3 text-sm";
const area="min-h-24 w-full rounded-lg border border-ink-900/10 bg-white p-3 text-sm";
const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;
export function AboutContentEditor({initial,gallery,videos}:{initial:AboutContentSettings;gallery:{value:string;label:string}[];videos:Pick<VideoAsset,"id"|"title"|"status">[]}){
 const [about,setAbout]=useState(initial); const section=<K extends keyof AboutContentSettings>(key:K,patch:Partial<AboutContentSettings[K]>)=>setAbout(v=>({...v,[key]:{...v[key],...patch}}));
 return <div className="space-y-5"><input type="hidden" name="about" value={JSON.stringify(about)}/>
 <section className="rounded-xl border bg-card p-4"><h2 className="font-black">هیرو درباره ما</h2><Enabled checked={about.hero.enabled} onChange={enabled=>section('hero',{enabled})}/><input className={input} value={about.hero.title} onChange={e=>section('hero',{title:e.target.value})} aria-label="عنوان هیرو"/><textarea className={`${area} mt-3`} value={about.hero.description} onChange={e=>section('hero',{description:e.target.value})} aria-label="توضیح هیرو"/></section>
 <section className="rounded-xl border bg-card p-4"><h2 className="font-black">معرفی</h2><Enabled checked={about.intro.enabled} onChange={enabled=>section('intro',{enabled})}/><input className={input} value={about.intro.heading} onChange={e=>section('intro',{heading:e.target.value})} aria-label="عنوان معرفی"/><div className="mt-4"><StructuredListEditor title="پاراگراف‌ها" items={about.intro.paragraphs} fields={[{key:'text',label:'متن',kind:'textarea'},{key:'active',label:'فعال',kind:'checkbox'}]} max={12} create={()=>({id:uid('paragraph'),text:'',active:true,order:0})} onChange={paragraphs=>section('intro',{paragraphs})}/></div></section>
 <section className="rounded-xl border bg-card p-4"><h2 className="font-black">گالری رسانه</h2><Enabled checked={about.gallery.enabled} onChange={enabled=>section('gallery',{enabled})}/><div className="space-y-4">{about.gallery.items.map((item,index)=><div key={item.id} className="rounded-xl bg-sand-50 p-3"><SiteMediaEditor label={`رسانه ${index+1}`} value={item.media} onChange={media=>section('gallery',{items:about.gallery.items.map((x,i)=>i===index?{...x,media}:x)})} gallery={gallery} videos={videos}/><input className={`${input} mt-3`} value={item.alt} onChange={e=>section('gallery',{items:about.gallery.items.map((x,i)=>i===index?{...x,alt:e.target.value}:x)})} placeholder="متن جایگزین"/><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={item.active} onChange={e=>section('gallery',{items:about.gallery.items.map((x,i)=>i===index?{...x,active:e.target.checked}:x)})}/> فعال</label><div className="mt-2 flex flex-wrap items-center gap-2"><ReorderControls index={index} count={about.gallery.items.length} onMove={delta=>section('gallery',{items:reorderItems(about.gallery.items,index,delta)})}/><button type="button" onClick={()=>section('gallery',{items:about.gallery.items.filter((_,i)=>i!==index).map((x,i)=>({...x,order:i}))})} className="mr-auto min-h-10 text-xs font-bold text-madder-700">حذف رسانه</button></div></div>)}<button type="button" disabled={about.gallery.items.length>=6} onClick={()=>section('gallery',{items:[...about.gallery.items,{id:uid('about-media'),media:{kind:'image',image:gallery[0]?.value||'/images/workshop-loom.jpg'},alt:'',active:true,order:about.gallery.items.length}]})} className="rounded-lg border px-4 py-2 text-sm font-bold">افزودن رسانه</button></div></section>
 <section className="rounded-xl border bg-card p-4"><h2 className="font-black">خط زمانی</h2><Enabled checked={about.timeline.enabled} onChange={enabled=>section('timeline',{enabled})}/><input className={input} value={about.timeline.title} onChange={e=>section('timeline',{title:e.target.value})} aria-label="عنوان خط زمانی"/><div className="mt-4"><StructuredListEditor title="رویدادها" items={about.timeline.items} fields={[{key:'year',label:'سال (متن فارسی)'},{key:'text',label:'شرح',kind:'textarea'},{key:'active',label:'فعال',kind:'checkbox'}]} max={30} create={()=>({id:uid('timeline'),year:'',text:'',active:true,order:0})} onChange={items=>section('timeline',{items})}/></div></section>
 <section className="rounded-xl border bg-card p-4"><h2 className="font-black">ارزش‌ها</h2><Enabled checked={about.values.enabled} onChange={enabled=>section('values',{enabled})}/><input className={input} value={about.values.title} onChange={e=>section('values',{title:e.target.value})} aria-label="عنوان ارزش‌ها"/><div className="mt-4"><StructuredListEditor title="ارزش‌ها" items={about.values.items} fields={[{key:'icon',label:'آیکن',kind:'select',options:[['hand-heart','قلب و دست'],['graduation-cap','آموزش'],['leaf','طبیعت'],['medal','مدال'],['star','ستاره'],['award','جایزه'],['shield','سپر'],['users','افراد']].map(([value,label])=>({value,label}))},{key:'title',label:'عنوان'},{key:'text',label:'توضیح',kind:'textarea'},{key:'active',label:'فعال',kind:'checkbox'}]} max={12} create={()=>({id:uid('value'),icon:'star',title:'',text:'',active:true,order:0})} onChange={items=>section('values',{items})}/></div></section>
 <section className="rounded-xl border bg-card p-4"><h2 className="font-black">دکمه‌های پایانی</h2>{about.ctas.map((cta,index)=><div key={index} className="mt-3 grid gap-3 sm:grid-cols-2"><input className={input} value={cta.label} onChange={e=>setAbout(v=>({...v,ctas:v.ctas.map((x,i)=>i===index?{...x,label:e.target.value}:x)}))} aria-label={`عنوان دکمه ${index+1}`}/><input className={input} value={cta.href} onChange={e=>setAbout(v=>({...v,ctas:v.ctas.map((x,i)=>i===index?{...x,href:e.target.value}:x)}))} dir="ltr" aria-label={`لینک دکمه ${index+1}`}/><label className="text-sm"><input type="checkbox" checked={cta.enabled} onChange={e=>setAbout(v=>({...v,ctas:v.ctas.map((x,i)=>i===index?{...x,enabled:e.target.checked}:x)}))}/> فعال</label></div>)}</section>
 </div>;
}
function Enabled({checked,onChange}:{checked:boolean;onChange:(value:boolean)=>void}){return <label className="my-3 flex gap-2 text-sm font-bold"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="accent-teal-700"/> نمایش بخش</label>}
