"use client";

import { useState } from "react";
import type { HomeContentSettings, Instructor, SiteMedia, VideoAsset } from "@/lib/types";
import { SiteMediaEditor } from "./SiteMediaEditor";
import { ReorderControls, reorderItems, StructuredListEditor, type EditorField } from "./StructuredListEditor";
import { UploadField } from "./UploadField";

const textItem:EditorField[]=[{key:"text",label:"متن",kind:"textarea"},{key:"active",label:"فعال",kind:"checkbox"}];
const statFields:EditorField[]=[{key:"value",label:"مقدار"},{key:"label",label:"عنوان"},{key:"hint",label:"توضیح کوتاه"},{key:"active",label:"فعال",kind:"checkbox"}];
const input="h-10 w-full rounded-lg border border-ink-900/10 bg-white px-3 text-sm";
const area="min-h-24 w-full rounded-lg border border-ink-900/10 bg-white p-3 text-sm";
const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;

export function HomeContentEditor({ initial, heroMedia, gallery, videos, instructors }: { initial:HomeContentSettings; heroMedia:SiteMedia; gallery:{value:string;label:string}[]; videos:Pick<VideoAsset,"id"|"title"|"status">[]; instructors:Pick<Instructor,"slug"|"name">[] }) {
 const [home,setHome]=useState(initial); const [media,setMedia]=useState(heroMedia);
 const section=<K extends keyof HomeContentSettings>(key:K,patch:Partial<HomeContentSettings[K]>)=>setHome(v=>({...v,[key]:{...v[key],...patch}}));
 return <div className="space-y-5"><input type="hidden" name="home" value={JSON.stringify(home)}/><input type="hidden" name="heroMedia" value={JSON.stringify(media)}/>
 <SiteMediaEditor label="رسانه هیرو" value={media} onChange={setMedia} gallery={gallery} videos={videos} allowUpload/>
 <details open className="rounded-xl border bg-card p-4"><summary className="cursor-pointer font-black">اعتماد و آمار</summary><label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={home.trust.enabled} onChange={e=>section('trust',{enabled:e.target.checked})}/> نمایش بخش</label><div className="mt-4 grid gap-4"><StructuredListEditor title="آمار" items={home.trust.stats} fields={statFields} max={12} create={()=>({id:uid('stat'),value:'',label:'',hint:'',active:true,order:0})} onChange={stats=>section('trust',{stats})}/><StructuredListEditor title="افتخارات" items={home.trust.honors} fields={textItem} max={20} create={()=>({id:uid('honor'),text:'',active:true,order:0})} onChange={honors=>section('trust',{honors})}/></div></details>
 <details className="rounded-xl border bg-card p-4"><summary className="cursor-pointer font-black">نقشه راه</summary><SectionEnabled checked={home.roadmap.enabled} onChange={enabled=>section('roadmap',{enabled})}/><ScalarGrid fields={[['eyebrow','برچسب'],['title','عنوان'],['description','توضیح'],['primaryCtaLabel','دکمه اصلی'],['primaryCtaHref','لینک اصلی'],['secondaryCtaLabel','دکمه دوم'],['secondaryCtaHref','لینک دوم']]} value={home.roadmap} onChange={(k,v)=>section('roadmap',{[k]:v})}/><StructuredListEditor title="چک‌لیست" items={home.roadmap.checklist} fields={textItem} max={10} create={()=>({id:uid('check'),text:'',active:true,order:0})} onChange={checklist=>section('roadmap',{checklist})}/><StructuredListEditor title="مراحل" items={home.roadmap.stages} fields={[{key:'title',label:'عنوان'},{key:'meta',label:'بازه/متا'},{key:'description',label:'توضیح',kind:'textarea'},{key:'active',label:'فعال',kind:'checkbox'}]} max={12} create={()=>({id:uid('stage'),title:'',meta:'',description:'',active:true,order:0})} onChange={stages=>section('roadmap',{stages})}/></details>
 <details className="rounded-xl border bg-card p-4"><summary className="cursor-pointer font-black">معرفی استاد</summary><SectionEnabled checked={home.spotlight.enabled} onChange={enabled=>section('spotlight',{enabled})}/><label className="block text-xs font-bold">مدرس منتخب<select className={`${input} mt-1`} value={home.spotlight.instructorSlug} onChange={e=>section('spotlight',{instructorSlug:e.target.value})}><option value="">مدرس ویژه یا اولین مدرس</option>{instructors.map(i=><option key={i.slug} value={i.slug}>{i.name}</option>)}</select></label><ScalarGrid fields={[['eyebrow','برچسب'],['quote','نقل‌قول'],['experienceLabel','عنوان سابقه'],['ctaLabel','عنوان دکمه'],['ctaHref','لینک دکمه']]} value={home.spotlight} onChange={(k,v)=>section('spotlight',{[k]:v})}/><StructuredListEditor title="آمار استاد" items={home.spotlight.stats} fields={statFields} max={8} create={()=>({id:uid('master-stat'),value:'',label:'',active:true,order:0})} onChange={stats=>section('spotlight',{stats})}/></details>
 <details className="rounded-xl border bg-card p-4"><summary className="cursor-pointer font-black">کارگاه اسدزاده</summary><SectionEnabled checked={home.workshop.enabled} onChange={enabled=>section('workshop',{enabled})}/><ScalarGrid fields={[['eyebrow','برچسب'],['title','عنوان'],['description','توضیح'],['ctaLabel','عنوان دکمه'],['ctaHref','لینک دکمه']]} value={home.workshop} onChange={(k,v)=>section('workshop',{[k]:v})}/><div className="space-y-4">{home.workshop.items.map((item,index)=><div key={item.id} className="rounded-xl bg-sand-50 p-3"><SiteMediaEditor label={`رسانه ${index+1}`} value={item.media} gallery={gallery} videos={videos} onChange={media=>section('workshop',{items:home.workshop.items.map((x,i)=>i===index?{...x,media}:x)})}/><div className="mt-3 grid gap-3 sm:grid-cols-2"><input className={input} value={item.alt} placeholder="متن جایگزین" onChange={e=>section('workshop',{items:home.workshop.items.map((x,i)=>i===index?{...x,alt:e.target.value}:x)})}/><input className={input} value={item.caption} placeholder="کپشن" onChange={e=>section('workshop',{items:home.workshop.items.map((x,i)=>i===index?{...x,caption:e.target.value}:x)})}/><label className="text-sm"><input type="checkbox" checked={item.active} onChange={e=>section('workshop',{items:home.workshop.items.map((x,i)=>i===index?{...x,active:e.target.checked}:x)})}/> فعال</label><div className="flex flex-wrap items-center gap-2"><ReorderControls index={index} count={home.workshop.items.length} onMove={delta=>section('workshop',{items:reorderItems(home.workshop.items,index,delta)})}/><button type="button" className="mr-auto min-h-10 text-xs font-bold text-madder-700" onClick={()=>section('workshop',{items:home.workshop.items.filter((_,i)=>i!==index).map((x,i)=>({...x,order:i}))})}>حذف</button></div></div></div>)}<button type="button" disabled={home.workshop.items.length>=12} onClick={()=>section('workshop',{items:[...home.workshop.items,{id:uid('workshop'),media:{kind:'image',image:gallery[0]?.value||'/images/workshop-loom.jpg'},alt:'',caption:'',active:true,order:home.workshop.items.length}]})} className="rounded-lg border px-4 py-2 text-sm font-bold">افزودن رسانه</button></div></details>
 <details className="rounded-xl border bg-card p-4"><summary className="cursor-pointer font-black">آثار هنرجویان</summary><SectionEnabled checked={home.studentWorks.enabled} onChange={enabled=>section('studentWorks',{enabled})}/><ScalarGrid fields={[['eyebrow','برچسب'],['title','عنوان'],['description','توضیح']]} value={home.studentWorks} onChange={(k,v)=>section('studentWorks',{[k]:v})}/>{home.studentWorks.items.map((item,index)=><div key={item.id} className="my-3 grid gap-3 rounded-xl bg-sand-50 p-3 sm:grid-cols-2"><input className={input} value={item.title} placeholder="عنوان اثر" onChange={e=>section('studentWorks',{items:home.studentWorks.items.map((x,i)=>i===index?{...x,title:e.target.value}:x)})}/><input className={input} value={item.studentName} placeholder="نام هنرجو" onChange={e=>section('studentWorks',{items:home.studentWorks.items.map((x,i)=>i===index?{...x,studentName:e.target.value}:x)})}/><UploadField name={`student-work-${item.id}`} label="تصویر اثر" gallery={gallery} initial={item.image} onValueChange={image=>section('studentWorks',{items:home.studentWorks.items.map((x,i)=>i===index?{...x,image}:x)})}/><input className={input} value={item.course} placeholder="دوره" onChange={e=>section('studentWorks',{items:home.studentWorks.items.map((x,i)=>i===index?{...x,course:e.target.value}:x)})}/><textarea className={area} value={item.description} placeholder="توضیح" onChange={e=>section('studentWorks',{items:home.studentWorks.items.map((x,i)=>i===index?{...x,description:e.target.value}:x)})}/><div className="flex flex-wrap items-center gap-2"><ReorderControls index={index} count={home.studentWorks.items.length} onMove={delta=>section('studentWorks',{items:reorderItems(home.studentWorks.items,index,delta)})}/><button type="button" onClick={()=>section('studentWorks',{items:home.studentWorks.items.filter((_,i)=>i!==index).map((x,order)=>({...x,order}))})} className="mr-auto min-h-10 text-xs font-bold text-madder-700">حذف</button></div></div>)}<button type="button" disabled={home.studentWorks.items.length>=20} onClick={()=>section('studentWorks',{items:[...home.studentWorks.items,{id:uid('student-work'),title:'',studentName:'',image:gallery[0]?.value||'',description:'',course:'',active:true,order:home.studentWorks.items.length}]})} className="rounded-lg border px-4 py-2 text-sm font-bold">افزودن اثر</button></details>
 <details className="rounded-xl border bg-card p-4"><summary className="cursor-pointer font-black">نظرات هنرجویان</summary><SectionEnabled checked={home.testimonials.enabled} onChange={enabled=>section('testimonials',{enabled})}/><ScalarGrid fields={[['eyebrow','برچسب'],['title','عنوان'],['description','توضیح']]} value={home.testimonials} onChange={(k,v)=>section('testimonials',{[k]:v})}/><StructuredListEditor title="نظرات" items={home.testimonials.items} fields={[{key:'name',label:'نام'},{key:'role',label:'سمت/دوره'},{key:'text',label:'نظر',kind:'textarea'},{key:'rating',label:'امتیاز',kind:'number',min:1,max:5},{key:'active',label:'فعال',kind:'checkbox'}]} max={20} create={()=>({id:uid('testimonial'),name:'',role:'',text:'',rating:5,active:true,order:0})} onChange={items=>section('testimonials',{items})}/></details>
 <details className="rounded-xl border bg-card p-4"><summary className="cursor-pointer font-black">دعوت پایانی</summary><SectionEnabled checked={home.finalCta.enabled} onChange={enabled=>section('finalCta',{enabled})}/><ScalarGrid fields={[['eyebrow','برچسب'],['title','عنوان'],['description','توضیح'],['primaryCtaLabel','عنوان دکمه'],['primaryCtaHref','لینک دکمه'],['phoneLabel','عنوان تلفن']]} value={home.finalCta} onChange={(k,v)=>section('finalCta',{[k]:v})}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={home.finalCta.showPhone} onChange={e=>section('finalCta',{showPhone:e.target.checked})}/> نمایش شماره تماس سایت</label></details>
 </div>;
}

function SectionEnabled({checked,onChange}:{checked:boolean;onChange:(value:boolean)=>void}){return <label className="my-4 flex gap-2 text-sm font-bold"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="accent-teal-700"/> نمایش این بخش</label>}
function ScalarGrid({fields,value,onChange}:{fields:[string,string][];value:object;onChange:(key:string,value:string)=>void}){const record=value as Record<string,unknown>;return <div className="my-4 grid gap-3 sm:grid-cols-2">{fields.map(([key,label])=><label key={key} className={key==='description'||key==='quote'?"sm:col-span-2":""}><span className="mb-1 block text-xs font-bold text-ink-600">{label}</span>{key==='description'||key==='quote'?<textarea className={area} value={String(record[key]??'')} onChange={e=>onChange(key,e.target.value)}/>:<input className={input} value={String(record[key]??'')} onChange={e=>onChange(key,e.target.value)}/>}</label>)}</div>}
