"use client";

import type { SiteMedia, VideoAsset } from "@/lib/types";
import { UploadField } from "./UploadField";
import { VideoUploader } from "./VideoUploader";

export function SiteMediaEditor({ label, value, onChange, gallery, videos, allowUpload=false }: { label:string; value:SiteMedia; onChange:(value:SiteMedia)=>void; gallery:{value:string;label:string}[]; videos:Pick<VideoAsset,"id"|"title"|"status">[]; allowUpload?:boolean }) {
 const kind=value.kind;
 return <fieldset className="space-y-3 rounded-xl border border-ink-900/10 p-4"><legend className="font-black text-navy-900">{label}</legend><div className="flex flex-wrap gap-4 text-sm font-bold">{([['image','تصویر'],['video','ویدیوی آپلودشده'],['embed','ویدیوی Embed']] as const).map(([k,l])=><label key={k} className="flex items-center gap-2"><input type="radio" checked={kind===k} onChange={()=>onChange(k==='image'?{kind:'image',image:gallery[0]?.value||'/images/hero-weaver.jpg',alt:''}:k==='video'?{kind:'video',videoId:'',autoplay:true,loop:true,muted:true}:{kind:'embed',src:'',title:'ویدیوی معرفی'})}/>{l}</label>)}</div>{kind==='image'?<><UploadField name={`media-image-${label}`} label="تصویر" gallery={gallery} initial={value.image} onValueChange={image=>onChange({...value,image})}/><input value={value.alt??''} onChange={e=>onChange({...value,alt:e.target.value})} placeholder="متن جایگزین تصویر" className="h-10 w-full rounded-lg border px-3 text-sm"/></>:kind==='video'?<><label className="block text-xs font-bold">ویدیوی آماده<select value={value.videoId} onChange={e=>onChange({...value,videoId:e.target.value})} className="mt-1 h-11 w-full rounded-lg border bg-white px-3 text-sm"><option value="">انتخاب کنید</option>{videos.filter(v=>v.status==='ready').map(v=><option key={v.id} value={v.id}>{v.title}</option>)}</select></label><UploadField name={`media-poster-${label}`} label="پوستر / تصویر جایگزین" gallery={gallery} initial={value.poster} onValueChange={poster=>onChange({...value,poster})}/><div className="flex flex-wrap gap-4 text-sm">{(['autoplay','loop','muted'] as const).map(key=><label key={key} className="flex items-center gap-2"><input type="checkbox" checked={key==='muted'&&value.autoplay?true:Boolean(value[key])} disabled={key==='muted'&&value.autoplay} onChange={e=>onChange({...value,[key]:e.target.checked,...(key==='autoplay'&&e.target.checked?{muted:true}:{})})}/>{key==='autoplay'?'پخش خودکار':key==='loop'?'تکرار':'بی‌صدا'}</label>)}</div>{allowUpload?<VideoUploader compact defaultTitle="ویدیوی بازاریابی" onUploaded={video=>onChange({...value,videoId:video.id})}/>:null}</>:<><input dir="ltr" value={value.src} onChange={e=>onChange({...value,src:e.target.value})} placeholder="https://www.aparat.com/video/video/embed/..." className="h-11 w-full rounded-lg border px-3 text-left text-sm"/><input value={value.title??''} onChange={e=>onChange({...value,title:e.target.value})} placeholder="عنوان قابل دسترس iframe" className="h-10 w-full rounded-lg border px-3 text-sm"/><p className="text-xs text-ink-500">فقط URL امن Aparat یا YouTube پذیرفته می‌شود؛ HTML مجاز نیست.</p></>}</fieldset>;
}
